Fix apache-commons-lang and junit dependencies.
errai/errai pull request #323
Opened 2017-12-15 15:05 UTC by hrstoyanov

This is a minor dependency clean up for stuff that needs to end up in the Earrai app war file.

2017-12-15 15:12 UTC, tiagobento commented
ok to test

2017-12-15 18:09 UTC, hrstoyanov commented
@tiagobento @mbarkley 
Can you help me understand which test failed? The ```Details``` link does not work.

I am battling a failing CodegenTest that does not work on Windows 7 or MacOS. Moist likely the reason is that I have Java 9 and Java 8 installed, the test is launching separate process that somehow seems to grab the wrong java and fails all the time. Untilli figure out why this is happening, just let me know what fails in the automatic checks

2017-12-15 20:02 UTC, mbarkley commented
@hrstoyanov Are you not receiving an email when the test fails? IIRC the email receives a public link that should be accessible to you.

2017-12-16 00:54 UTC, hrstoyanov commented
@mbarkley 
I did receive email on Dec 7 for a prior pull request. Nothing for this one? And not even in my spam folder.

2017-12-16 21:39 UTC, hrstoyanov commented
ok to test

2017-12-18 08:02 UTC, hrstoyanov commented
Can someone take a look at why tests fail? I ran the pull request branch in a clean  OpenJDK 8 docker container and all tests passed...

2017-12-19 19:15 UTC, tiagobento commented
Jenkins, please retest this

2017-12-19 19:23 UTC, hrstoyanov commented
@tiagobento thanks, if it fails again, pls tell me where

2017-12-21 06:10 UTC, hrstoyanov commented
Maven war plugin fails in a way that I can not figure out:

**mvn -e -s settings.xml install test** 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war (default-war) on project errai-bus-demo-stress-test: Failed to copy file for artifact [org.jboss.errai:errai-bus:jar:4.1.3-SNAPSHOT:compile]: /errai/err
ai-bus/target/classes (Is a directory) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war (default-war) on project errai-bus-demo-stress-test: Failed to copy file for artifact [org.jboss.errai:e
rrai-bus:jar:4.1.3-SNAPSHOT:compile]
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to copy file for artifact [org.jboss.errai:errai-bus:jar:4.1.3-SNAPSHOT:compile]
    at org.apache.maven.plugin.war.packaging.ArtifactsPackagingTask.performPackaging (ArtifactsPackagingTask.java:131)
    at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.handleArtifacts (WarProjectPackagingTask.java:189)
    at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.performPackaging (WarProjectPackagingTask.java:108)
    at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp (AbstractWarMojo.java:472)
    at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp (AbstractWarMojo.java:404)
    at org.apache.maven.plugin.war.WarMojo.performPackaging (WarMojo.java:197)
    at org.apache.maven.plugin.war.WarMojo.execute (WarMojo.java:159)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.io.FileNotFoundException: /errai/errai-bus/target/classes (Is a directory)
    at java.io.FileInputStream.open0 (Native Method)
    at java.io.FileInputStream.open (FileInputStream.java:195)
    at java.io.FileInputStream.<init> (FileInputStream.java:138)
    at org.codehaus.plexus.util.io.FileInputStreamFacade.getInputStream (FileInputStreamFacade.java:39)
    at org.codehaus.plexus.util.FileUtils.copyStreamToFile (FileUtils.java:1106)
    at org.codehaus.plexus.util.FileUtils.copyFile (FileUtils.java:1013)
    at org.apache.maven.plugin.war.packaging.AbstractWarPackagingTask.copyFile (AbstractWarPackagingTask.java:293)
    at org.apache.maven.plugin.war.packaging.AbstractWarPackagingTask$1.registered (AbstractWarPackagingTask.java:150)
    at org.apache.maven.plugin.war.util.WebappStructure.registerFile (WebappStructure.java:211)
    at org.apache.maven.plugin.war.packaging.AbstractWarPackagingTask.copyFile (AbstractWarPackagingTask.java:145)
    at org.apache.maven.plugin.war.packaging.ArtifactsPackagingTask.performPackaging (ArtifactsPackagingTask.java:106)
    at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.handleArtifacts (WarProjectPackagingTask.java:189)
    at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.performPackaging (WarProjectPackagingTask.java:108)
    at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp (AbstractWarMojo.java:472)
    at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp (AbstractWarMojo.java:404)
    at org.apache.maven.plugin.war.WarMojo.performPackaging (WarMojo.java:197)
    at org.apache.maven.plugin.war.WarMojo.execute (WarMojo.java:159)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apach [...]

2018-01-02 16:17 UTC, mbarkley commented
Not sure where that error you pasted comes from, but the problem on Jenkins appears to be a missing `org.apache.commons.lang3.StringUtils` in the Errai Bus Websocket Weld tests that causes the build to hang.

2018-01-03 02:33 UTC, hrstoyanov commented
@mbarkley 
At a loss here ... running off my branch ```https://github.com/hrstoyanov/errai/tree/dependencies_cleanup``` produces no failed test. Also, if you look at the ```Errai:: Bus:JSR-356::WebSocket::Weld``` in the above branch, there is no reference to ```org.apache.commons.lang3.StringUtils``` anywhere in the unit tests at all?

Is there any chance Jenkins is pulling old patch and not the latest in the pull request?

2018-07-31 13:44 UTC, tiagobento commented
Jenkins please retest this.

2018-08-06 16:40 UTC, hrstoyanov commented
@tiagobento will take care of it next 1-2 days! As a remainder, the goal of this patch is to get rid of 3-4 jars with weak reasons to be used.

2018-08-16 20:09 UTC, kiereleaseuser2 commented
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

2018-08-16 20:29 UTC, hrstoyanov commented
i still have not found the time to fix it, maybe this week

2018-08-17 04:15 UTC, kiereleaseuser2 commented
Build finished. No test results found.

2019-06-04 18:19 UTC, kiereleaseuser2 commented
Build finished. 187 tests run, 1 skipped, 6 failed.

2020-11-03 13:12 UTC, mareknovotny commented
Jenkins retest this please

2020-11-03 13:53 UTC, mareknovotny commented on errai-common/pom.xml
this dependency removal is not handled here in the PR correctly. There are multiple usages of commons-lang3 classes as transitive dependencies in errai-codegen or somewhere else too

2020-11-03 13:54 UTC, mareknovotny requested changes
There are compiler errors due removal of apache commons-lang3 dependency

2022-09-29 09:45 UTC, mareknovotny commented
outdated PR, so closing now

2022-09-29 09:45 UTC, closed without merging